# Generated by Django 5.1.7 on 2025-04-24 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='supplier_logos/')),
                ('status', models.CharField(choices=[('active', 'متاح'), ('inactive', 'غير متاح')], max_length=10)),
                ('supply_sector', models.CharField(choices=[('retail', 'بيع بالتجزئة'), ('wholesale', 'بالجملة'), ('both', 'كلاهما')], max_length=50)),
                ('delivery_service', models.CharField(choices=[('fast', 'سريع'), ('shipping', 'شحن'), ('both', 'كلاهما')], max_length=50)),
                ('order_lead_time_days', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('unavailable_from', models.DateTimeField(blank=True, null=True)),
                ('unavailable_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official_holidays', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_description', models.TextField()),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.CharField(max_length=255)),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='commercial_documents/')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='commercial_documents/')),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='commercial_documents/')),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('commercial_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('commercial_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('commercial_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_info', to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('supplier', models.ManyToManyField(related_name='branches', to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fast_service_details', models.CharField(blank=True, max_length=255)),
                ('late_payment_options', models.BooleanField(default=False)),
                ('supply_days', models.CharField(help_text="Days the supplier is available to supply (e.g., 'Saturday to Thursday')", max_length=100)),
                ('supply_type', models.CharField(choices=[('on_demand', 'On-Demand'), ('scheduled', 'Scheduled'), ('both', 'Both')], default='scheduled', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_method', to='supplier.supplier')),
            ],
        ),
    ]
