# Generated by Django 5.2 on 2025-05-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(1, 'السبت'), (2, 'الاحد'), (3, 'الاثنين'), (4, 'الثلاثاء'), (5, 'الاربعاء'), (6, 'الخميس'), (7, 'الجمعة')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('riyadh', 'الرياض'), ('jeddah', 'جدة'), ('mecca', 'مكة'), ('medina', 'المدينة'), ('dammam', 'الدمام'), ('khobar', 'الخبر'), ('tabuk', 'تبوك'), ('abha', 'أبها'), ('hail', 'حائل'), ('najran', 'نجران')], max_length=100)),
                ('suppliers', models.ManyToManyField(related_name='cities_covered', to='accounts.supplierprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_description', models.TextField()),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='Media/commercial_documents/')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='Media/commercial_documents/')),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='Media/commercial_documents/')),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('commercial_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('commercial_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('commercial_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_info', to='accounts.supplierprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='supplier_logos/')),
                ('supply_sector', models.CharField(choices=[('retail', 'بيع بالتجزئة'), ('wholesale', 'بالجملة'), ('both', 'بيع تجزئة وجملة')], max_length=50)),
                ('delivery_service', models.CharField(choices=[('fast', 'سريع'), ('shipping', 'شحن'), ('both', 'توصيل سريع وشحن')], max_length=50)),
                ('order_lead_time_days', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('unavailable_from', models.DateTimeField(blank=True, null=True)),
                ('unavailable_to', models.DateTimeField(blank=True, null=True)),
                ('fast_service_details', models.IntegerField(blank=True, null=True)),
                ('late_payment_options', models.BooleanField(default=False)),
                ('supply_type', models.CharField(choices=[('on_demand', 'حسب الطلب'), ('scheduled', 'مجدول'), ('both', 'حسب الطلب ومجدول')], default='scheduled', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_details', to='accounts.supplierprofile')),
                ('supply_days', models.ManyToManyField(to='supplier.day')),
            ],
        ),
    ]
