# Generated by Django 5.2 on 2025-04-23 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=255)),
                ('store_description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('supply_sector', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('both', 'Both')], max_length=50)),
                ('delivery_service', models.CharField(choices=[('fast', 'Fast'), ('shipping', 'Shipping'), ('both', 'Both')], max_length=50)),
                ('fast_service_details', models.CharField(blank=True, max_length=255)),
                ('order_lead_time_days', models.IntegerField()),
                ('late_payment_options', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('unavailable_from', models.DateTimeField(blank=True, null=True)),
                ('unavailable_to', models.DateTimeField(blank=True, null=True)),
                ('store_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official_holidays', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='Media/')),
                ('min_stock_alert', models.IntegerField(default=0)),
                ('category_type', models.CharField(choices=[], max_length=20)),
                ('product_subcategory', models.CharField(choices=[], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='supplier.supplier')),
            ],
        ),
    ]
