# Generated by Django 5.2 on 2025-04-24 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='official_holidays',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='status',
        ),
        migrations.AddField(
            model_name='supplier',
            name='fast_service_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='late_payment_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply_days',
            field=models.CharField(default='', help_text="Days the supplier is available to supply (e.g., 'Saturday to Thursday')", max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(choices=[('riyadh', 'الرياض'), ('jeddah', 'جدة'), ('mecca', 'مكة'), ('medina', 'المدينة'), ('dammam', 'الدمام'), ('khobar', 'الخبر'), ('tabuk', 'تبوك'), ('abha', 'أبها'), ('hail', 'حائل'), ('najran', 'نجران')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='order_lead_time_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SupplyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(choices=[('on_demand', 'On-Demand'), ('scheduled', 'Scheduled'), ('both', 'Both')], default='scheduled', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_method', to='supplier.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='SupplyMethod',
        ),
        migrations.AddField(
            model_name='branch',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='supplier.supplier'),
            preserve_default=False,
        ),
    ]
