# Generated by Django 5.2 on 2025-04-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_official_holidays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('rejected', 'رفض'), ('accepted', 'مقبول'), ('pending', 'قيد المعالجة')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='commercialinfo',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='Media/commercial_documents/'),
        ),
        migrations.AlterField(
            model_name='commercialinfo',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='Media/commercial_documents/'),
        ),
        migrations.AlterField(
            model_name='commercialinfo',
            name='tax_certificate',
            field=models.FileField(blank=True, null=True, upload_to='Media/commercial_documents/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Media/supplier_logos/'),
        ),
        migrations.AlterField(
            model_name='supplydetail',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_detail', to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='supplydetail',
            name='supply_type',
            field=models.CharField(choices=[('on_demand', 'حسب الطلب'), ('scheduled', 'مجدول'), ('both', 'كلاهما')], default='scheduled', max_length=50),
        ),
    ]
