# Generated by Django 5.1.7 on 2025-04-28 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_rejection_reason_supplier_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialinfo',
            name='is_verified',
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبولة'), ('rejected', 'مرفوضة')], default='pending', max_length=255)),
                ('commercialInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.commercialinfo')),
            ],
        ),
    ]
