# Generated by Django 5.2 on 2025-04-28 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_commercialinfo_is_verified_supplyrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='SupplyDetails',
        ),
    ]
