# Generated by Django 5.2 on 2025-04-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profilebeneficiary_user_and_more'),
        ('supplier', '0005_rename_supplier_supplydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialinfo',
            name='store_address',
        ),
        migrations.AlterField(
            model_name='commercialinfo',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_info', to='accounts.supplierprofile'),
        ),
    ]
