# Generated by Django 5.2 on 2025-04-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_supplierprofile_rejection_reason_and_more'),
        ('supplier', '0006_remove_commercialinfo_store_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplydetails',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='supplydetails',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supplydetails',
            name='user',
        ),
        migrations.AddField(
            model_name='supplydetails',
            name='supplier',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='supply_details', to='accounts.supplierprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplydetails',
            name='supply_type',
            field=models.CharField(choices=[('on_demand', 'حسب الطلب'), ('scheduled', 'مجدول'), ('both', 'كلاهما')], default='scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplydetails',
            name='fast_service_details',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplydetails',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_logos/'),
        ),
        migrations.DeleteModel(
            name='SupplyDetail',
        ),
    ]
