# Generated by Django 5.2 on 2025-04-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_supplierprofile_rejection_reason_and_more'),
        ('supplier', '0007_remove_supplydetails_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('riyadh', 'الرياض'), ('jeddah', 'جدة'), ('mecca', 'مكة'), ('medina', 'المدينة'), ('dammam', 'الدمام'), ('khobar', 'الخبر'), ('tabuk', 'تبوك'), ('abha', 'أبها'), ('hail', 'حائل'), ('najran', 'نجران')], default='riyadh', max_length=50)),
                ('city', models.CharField(choices=[('riyadh', 'الرياض'), ('jeddah', 'جدة'), ('mecca', 'مكة'), ('medina', 'المدينة'), ('dammam', 'الدمام'), ('khobar', 'الخبر'), ('tabuk', 'تبوك'), ('abha', 'أبها'), ('hail', 'حائل'), ('najran', 'نجران')], max_length=100)),
                ('suppliers', models.ManyToManyField(related_name='cities_covered', to='accounts.supplierprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
