# Generated by Django 5.2 on 2025-04-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_city_delete_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
    ]
