# Generated by Django 5.2 on 2025-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_remove_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplydetails',
            name='delivery_service',
            field=models.CharField(choices=[('fast', 'سريع'), ('shipping', 'شحن'), ('both', 'توصيل سريع وشحن')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supplydetails',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplydetails',
            name='supply_sector',
            field=models.CharField(choices=[('retail', 'بيع بالتجزئة'), ('wholesale', 'بالجملة'), ('both', 'بيع تجزئة وجملة')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supplydetails',
            name='supply_type',
            field=models.CharField(choices=[('on_demand', 'حسب الطلب'), ('scheduled', 'مجدول'), ('both', 'حسب الطلب ومجدول')], default='scheduled', max_length=50),
        ),
        migrations.DeleteModel(
            name='SupplyRequest',
        ),
    ]
