# Generated by Django 5.2 on 2025-05-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_alter_supplydetails_delivery_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(1, 'السبت'), (2, 'الاحد'), (3, 'الاثنين'), (4, 'الثلاثاء'), (5, 'الاربعاء'), (6, 'الخميس'), (7, 'الجمعة')])),
            ],
        ),
        migrations.RemoveField(
            model_name='supplydetails',
            name='supply_days',
        ),
        migrations.AddField(
            model_name='supplydetails',
            name='supply_days',
            field=models.ManyToManyField(blank=True, to='supplier.day'),
        ),
    ]
