# Generated by Django 5.2 on 2025-05-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0011_day_remove_supplydetails_supply_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='supplydetails',
            name='supply_days',
            field=models.ManyToManyField(to='supplier.day'),
        ),
    ]
