# Generated by Django 5.2 on 2025-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0012_alter_day_name_alter_supplydetails_supply_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[(1, 'السبت'), (2, 'الاحد'), (3, 'الاثنين'), (4, 'الثلاثاء'), (5, 'الاربعاء'), (6, 'الخميس'), (7, 'الجمعة')], max_length=20, unique=True),
        ),
    ]
