# Generated by Django 5.2 on 2025-05-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقداً'), ('credit', 'بطاقة ائتمان'), ('deferred', 'دفع آجل')], default='cash', max_length=20),
        ),
    ]
