# Generated by Django 5.2 on 2025-05-07 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('city', models.CharField(choices=[('riyadh', 'الرياض'), ('jeddah', 'جدة'), ('mecca', 'مكة'), ('medina', 'المدينة'), ('dammam', 'الدمام'), ('khobar', 'الخبر'), ('tabuk', 'تبوك'), ('abha', 'أبها'), ('hail', 'حائل'), ('najran', 'نجران')], default='riyadh', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('No-request', 'لا يوجد طلب'), ('Rejected', 'مرفوض'), ('Accepted', 'مقبول'), ('Pending', 'قيد المعالجة')], default='No-request', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
