# Generated by Django 5.2 on 2025-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_supplierprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierprofile",
            name="name",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
