# Generated by Django 5.2 on 2025-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_supplierprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierprofile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
