# Generated by Django 5.2 on 2025-04-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profilebeneficiary_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='status',
            field=models.CharField(choices=[('No-request', 'لا يوجد طلب'), ('Rejected', 'مرفوص'), ('Accepted', 'مقبول'), ('Pending', 'قيد المعالجة')], default='No-request', max_length=10),
        ),
    ]
