# Generated by Django 5.2 on 2025-04-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_supplierprofile_is_active"),
        ("accounts", "0005_supplierprofile_rejection_reason_and_more"),
    ]

    operations = []
