# Generated by Django 5.2 on 2025-04-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_20250429_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("No-request", "لا يوجد طلب"),
                    ("Rejected", "مرفوض"),
                    ("Accepted", "مقبول"),
                    ("Pending", "قيد المعالجة"),
                ],
                default="No-request",
                max_length=10,
            ),
        ),
    ]
