# Generated by Django 5.2 on 2025-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_supplierprofile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilebeneficiary",
            name="address",
        ),
        migrations.AddField(
            model_name="profilebeneficiary",
            name="city",
            field=models.CharField(
                choices=[
                    ("riyadh", "الرياض"),
                    ("jeddah", "جدة"),
                    ("mecca", "مكة"),
                    ("medina", "المدينة"),
                    ("dammam", "الدمام"),
                    ("khobar", "الخبر"),
                    ("tabuk", "تبوك"),
                    ("abha", "أبها"),
                    ("hail", "حائل"),
                    ("najran", "نجران"),
                ],
                default="riyadh",
                max_length=20,
            ),
        ),
    ]
