# Generated by Django 5.2 on 2025-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_in_cart_order_supplier_alter_order_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
