# Generated by Django 5.2 on 2025-05-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_profilebeneficiary_address_and_more"),
        ("order", "0002_order_supplier_alter_order_beneficiary"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="in_cart",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_orders",
                to="accounts.supplierprofile",
            ),
        ),
    ]
