# Generated by Django 5.2 on 2025-05-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_in_cart_alter_order_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "مفتوح"),
                    ("processing", "قيد المعالجة"),
                    ("closed", "مستلم"),
                    ("cancelled", "ملغاة"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
