# Generated by Django 5.2 on 2025-05-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_delivery_date'),
        ('order', '0005_alter_order_delivery_date'),
    ]

    operations = [
    ]
