# Generated by Django 5.2 on 2025-05-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_merge_20250506_0058"),
        ("order", "0006_merge_20250506_1052"),
    ]

    operations = []
