# Generated by Django 5.2 on 2025-05-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_cartitem_subtotal"),
        ("order", "0007_merge_20250506_1957"),
    ]

    operations = []
