# Generated by Django 5.2 on 2025-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='Media/')),
                ('min_stock_alert', models.IntegerField(default=0)),
                ('min_order_quantity', models.IntegerField(default=1)),
                ('sale_method', models.CharField(choices=[('unit', 'حبة'), ('kg', 'كيلو'), ('carton', 'كرتون'), ('box', 'صندوق'), ('liter', 'للتر'), ('packet', 'بالعبوة'), ('set', 'بالمجموعة'), ('pound', 'بالرطل'), ('bag', 'بالكيس')], max_length=20)),
                ('category', models.CharField(choices=[('agricultural', 'المنتجات الزراعية'), ('processed', 'المنتجات الغذائية المصنعة'), ('industrial', 'المنتجات الصناعية'), ('special', 'المنتجات الخاصة'), ('miscellaneous', 'منتجات متنوعة')], max_length=20)),
                ('subcategory', models.CharField(choices=[], max_length=20)),
                ('ingredients', models.TextField(blank=True)),
                ('nutrition_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
