# Generated by Django 5.2 on 2025-05-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('agricultural', 'المنتجات الزراعية'), ('processed', 'المنتجات الغذائية المصنعة'), ('industrial', 'المنتجات الصناعية'), ('special', 'المنتجات الخاصة'), ('miscellaneous', 'منتجات متنوعة')], max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='product-img/')),
                ('min_stock_alert', models.IntegerField(default=0)),
                ('min_order_quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(choices=[('unit', 'حبة'), ('kg', 'كيلو'), ('carton', 'كرتون'), ('box', 'صندوق'), ('liter', 'للتر'), ('packet', 'بالعبوة'), ('set', 'بالمجموعة'), ('pound', 'بالرطل'), ('bag', 'بالكيس')], max_length=20)),
                ('category', models.CharField(choices=[('agricultural', 'المنتجات الزراعية'), ('processed', 'المنتجات الغذائية المصنعة'), ('industrial', 'المنتجات الصناعية'), ('special', 'المنتجات الخاصة'), ('miscellaneous', 'منتجات متنوعة')], max_length=20)),
                ('subcategory', models.CharField(choices=[], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('City', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supplier.city')),
            ],
        ),
    ]
