# Generated by Django 5.2 on 2025-04-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_method',
            new_name='unit',
        ),
    ]
