# Generated by Django 5.2 on 2025-04-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_sale_method_product_unit'),
        ('supplier', '0010_alter_supplydetails_delivery_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='City',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supplier.city'),
            preserve_default=False,
        ),
    ]
