# Generated by Django 5.2 on 2025-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('agricultural', 'المنتجات الزراعية'), ('processed', 'المنتجات الغذائية المصنعة'), ('industrial', 'المنتجات الصناعية'), ('special', 'المنتجات الخاصة'), ('miscellaneous', 'منتجات متنوعة')], max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
    ]
