# Generated by Django 5.2 on 2025-05-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
