# Generated by Django 5.2 on 2025-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_reportreply_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportreply",
            name="is_admin_reply",
            field=models.BooleanField(default=False),
        ),
    ]
